version: '3'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - ${POSTGRE_PORTS}
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    

# volumes:
#   pgdata:
#   type: volume